### ISSUE TITLE
Made a Web App

### ISSUE THREAD

**Issue by antfu** [ElaWorkshop/awesome-cn-cafe#168]
Thanks for making this and it helped me find some good local cafe.

The Github rendered maps are not bad, but I found myself hard to find pins nearby. So I made a web app for this awesome list, providing better browsing and searching with your current location.

Repo: https://github.com/antfu/awesome-cn-cafe-web
App: https://cafe-cn.netlify.app/

It would be great if it can be featured in the readme and helps others :P

**Comment by yihong0618** [comment]
@antfu 
Cool web app, I think  would it be nicer to mark the number of city.
Something like below

![image](https://user-images.githubusercontent.com/15976103/89533836-9b0e8b80-d826-11ea-8aeb-00db20e7ecc9.png)

**Comment by antfu** [comment]
@yihong0618 I have never zoomed that far 🤣. yeah, that's a cool idea, will do. Thanks :)

**Comment by yihong0618** [comment]
@antfu 
mapbox geojson example, I think its fun.
https://github.com/tidwall/geojson/blob/master/test_files/boston_subset.geojson

**Comment by xhacker** [comment]
Great, thanks! The rendering has some problems on Safari. Can you take a look?

<img width="929" alt="截屏2020-08-06 下午10 16 02" src="https://user-images.githubusercontent.com/1051813/89542621-7d472380-d832-11ea-8167-003933363559.png">

**Comment by xhacker** [comment]
> @antfu
> mapbox geojson example, I think its fun.
> https://github.com/tidwall/geojson/blob/master/test_files/boston_subset.geojson

Do you know if it’s possible to have the same grouping on our geoJSON?

**Comment by xhacker** [comment]
> @antfu
> mapbox geojson example, I think its fun.
> https://github.com/tidwall/geojson/blob/master/test_files/boston_subset.geojson

@yihong0618 Do you know if it’s possible to have the same grouping on our geoJSON?

**Comment by antfu** [comment]
@xhacker Do you have any steps to reproduce it? It looks fine to me

![image](https://user-images.githubusercontent.com/11247099/89543077-12e2b300-d833-11ea-8389-461988a2bf68.png)

**Comment by xhacker** [comment]
@antfu Simply open the website… I can reproduce about 50% of the time. Weird.

**Comment by xhacker** [comment]
Updated README.md. Thanks again for the app!

**Comment by antfu** [comment]
@yihong0618 Clusters just get supported

@xhacker Safari is kinda weird, but I think I have managed to fix it. :)

Thanks for all the feedback.

**Comment by yihong0618** [comment]
@xhacker Sorry I did not use it before, but I think it is possible .
@antfu  that is really cool.
