### ISSUE TITLE
readme 中获取坐标的方法失效

### ISSUE THREAD

**Issue by lhysdl** [ElaWorkshop/awesome-cn-cafe#177]
### 1. “Mapbox 的显示经纬度来获取经纬度” 
[显示经纬度](https://www.mapbox.com/mapbox.js/example/v1.0.0/select-center-form/)页面中没找到获取当前经纬度的方法。
### 2.如果你正在咖啡馆并且可以翻墙，可以使用 whereami 来获得当前经纬度。
[whereami ](https://xavierchow.github.io/whereami/)，翻墙后会定位到vpn节点所在地。
### 3.请用 Speedtest 或其他工具测试网络速度
今天也发生了偏移的情况。

**Comment by xhacker** [comment]
你好，对 README 做了一些修改。你说的定位不准可能是因为周围的 Wi-Fi 热点比较少。如果用手机定位应该会更准一些。
