### ISSUE TITLE
How about adding some pictures for cafe

### ISSUE THREAD

**Issue by xavierchow** [ElaWorkshop/awesome-cn-cafe#18]
If someone takes pictures for the cafe, it can be shared in the tooltip of the marker, sth like:
<img width="300" alt="screenshot 2016-02-20 18 43 13" src="https://cloud.githubusercontent.com/assets/2748884/13196188/6e206b9e-d802-11e5-8e3b-b0e28a07d329.png">

Here's a [sample](https://www.mapbox.com/mapbox.js/example/v1.0.0/custom-marker-tooltip/) we can leverage.

Note the geojson doesn't support to embed image in marker, we need to generate(of course it should be automatic) some htmls(maybe [gh-page](https://help.github.com/articles/creating-project-pages-manually/) will be a good place to server them)

**Comment by xhacker** [comment]
Making a full-fledged website is beyond my expectation for this project. I’d keep it simple and see what we can get by using geoJSON and GitHub. :)

Actually, one feature I can think about is adding Foursquare (or Dianping, or whatever) links to geoJSON.

**Comment by xavierchow** [comment]
Okay, it's fine to adhere to KISS principle, about the links  I think it's free to add them to geoJSON.
