### ISSUE TITLE
这个网速是硬指标么？

### ISSUE THREAD

**Issue by mshhmzh** [ElaWorkshop/awesome-cn-cafe#37]
广州很多不错的精品咖啡店。我也去过一些，曾经也有测速，现在已经找不到曾经的测速结果了。这些店的分布都很广，再让我一个一个去测速有点不太实际...但是这些精品咖啡店非常值得推荐，我可以先将这些店的都加上，让后续有人去之后再补上测速的部分么？

**Comment by xhacker** [comment]
最好还是有网速再提交吧，不然跟其他点评站点区别就不大了……
