### ISSUE TITLE
The color hex in README is inconsistent with housekeeper script

### ISSUE THREAD

**Issue by xavierchow** [ElaWorkshop/awesome-cn-cafe#48]
Though the subtle difference is nearly unrecognizable,  we'd better stick into one, as most of geojsons have already been using the values in housekeeper, I'm gonna send a PR for README updating.
* README:
```
#BF4743
#F0AC31
#54BF47
```
* housekeeper.js:
```
#C24740
#F3AE1A
#50C240
```

**Comment by xhacker** [comment]
Totally agree.

**Comment by xavierchow** [comment]
merged, closing.
