### ISSUE TITLE
Apply auto lint for geojson

### ISSUE THREAD

**Issue by xavierchow** [ElaWorkshop/awesome-cn-cafe#54]
Considering we often receive malformed geojsons in PR, and it's inefficient to check manually.
I'm thinking to setup a CI for geojson linting, what do you think? @xhacker 
If there's no objection could you enable the [Travis-CI](https://travis-ci.org/profile/ElaWorkshop) for this repo? I can setup the lint for it.

**Comment by AquarHEAD** [comment]
Enabled

**Comment by xavierchow** [comment]
Thanks, done, closing

**Comment by xhacker** [comment]
Awesome!
