### ISSUE TITLE
建议将 SpeedTest 的测速 app 设为推荐用测试工具，取代网页版测试以及坐标获取工具

### ISSUE THREAD

**Issue by crispgm** [ElaWorkshop/awesome-cn-cafe#60]
原因：
1. 跟 SpeedTest 网页测试一家的，测速没什么问题
2. 可以获取坐标（至少 iPhone 版有此功能，没有 Android 不清楚那边情况），如附图所示，不再需要使用 Mapbox 或需要翻墙的工具
3. 移动测试比较方便，毕竟不是每次去咖啡都带电脑

![image](https://cloud.githubusercontent.com/assets/1425636/16901241/57d08634-4c70-11e6-9494-03317c5e915c.png)

因为涉及到“贡献”和“注意”两个段落，就没直接 PR。
请 Maintainers 考虑下。

**Comment by AquarHEAD** [comment]
> 请用 Speedtest 或其他工具测试网络速度
這句話本身就包含了 Speedtest.app 吧...

**Comment by crispgm** [comment]
@AquarHEAD 这么说是的。只是今天才发现这货还能把坐标也搞定，简直一站式略科学。

**Comment by HarukaMa** [comment]
还好这个获取到的坐标可以配合 OSM 一起用……

我觉得其实可以直接 PR 进 readme 里……
