### ISSUE TITLE
Host a PR check service by our own

### ISSUE THREAD

**Issue by aquarhead** [ElaWorkshop/awesome-cn-cafe#86]
For faster response, maybe...

**Comment by Cee** [comment]
Just validate .geojson file?

**Comment by aquarhead** [comment]
this https://help.github.com/articles/enabling-required-status-checks/

**Comment by aquarhead** [comment]
actually this https://help.github.com/articles/about-required-status-checks/

**Comment by xhacker** [comment]
Travis CI is actually super fast nowadays.
